version: '3.8'
services:
  app:
    build: .
    container_name: node-app
    ports:
      - "3001:3000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: avanzata
      POSTGRES_DB: checkers_game
    ports:
      - "5432:5432"
