services:
  app:
    build: .
    container_name: node-app
    ports:
      - "3001:3000"
    depends_on:
      - db
    env_file:
      - .env
    command: npm start

  db:
    image: postgres:13
    container_name: postgres-database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"