services:
  app:
    build: .
    container_name: node-app
    ports:
      - "3001:3000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      bash -c "
      sleep 1 &&
            ./wait-for-it.sh db:5432 --timeout=60 --strict -- 
      npx sequelize-cli db:migrate:undo:all --config src/database/config.js &&
      npx sequelize-cli db:migrate --config src/database/config.js --migrations-path src/database/migrations &&
      npx sequelize-cli db:seed:undo:all --config src/database/config.js --seeders-path src/database/seeders &&
      npx sequelize-cli db:seed:all --config src/database/config.js --seeders-path src/database/seeders &&
      npm start"

  db:
    image: postgres:13
    container_name: postgres-database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"